// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetAndReact.Data;

namespace aspnetAndReact.Migrations
{
    [DbContext(typeof(GGContext))]
    [Migration("20181117011030_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("aspnetAndReact.Data.GoalDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateAchieved");

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Desc");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("aspnetAndReact.Data.PostDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("DateCreated");

                    b.Property<int?>("GoalDTOID");

                    b.Property<string>("Header")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("GoalDTOID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("aspnetAndReact.Data.UserDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Age");

                    b.Property<DateTime>("DateChanged");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateDeleted");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Sex");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("aspnetAndReact.Data.PostDTO", b =>
                {
                    b.HasOne("aspnetAndReact.Data.GoalDTO")
                        .WithMany("Posts")
                        .HasForeignKey("GoalDTOID");
                });
#pragma warning restore 612, 618
        }
    }
}
